@api = http://localhost:3000/dtll_prof_cur

### Trae todos los detalles de los cursos con los profesores
GET {{api}}

### Crear un detalle profesor Curso
POST {{api}}
Content-Type: application/json

{
    "id_usuario":2,
    "id_curso":1
}

### Trae un detalle de los cursos con los profesores por ID 
GET {{api}}/2

### Elimina detalle de los cursos con los profesores cursos por ID
DELETE {{api}}/3

### Actualizar los datos de los detalles profesor curso por id 
PUT {{api}}/4
Content-Type: application/json

{
    "id_usuario": 2,
    "id_cursos": 1
}
