@api = http://localhost:3000/users

### Pidiendo todos los usuarios
GET {{api}}

### Agregando un usuario
POST {{api}} 
Content-Type: application/json

{
    "nombre": "Juan",
    "apellido": "Londoño",
    "correo": "juanlodonoierml@gmail.com",
    "correo_respaldo": "Eladmin@soy.sena.edu.co",
    "num_documento": "0000000000",
    "num_contrato": "0000000",
    "num_contacto": "0000000000",
    "contrasena": "1234",
    "estado_usuario": 1
}

### Pedir un usuario por ID
GET {{api}}/2

### Eliminando un Producto
DELETE {{api}}/24

### Traer el total de los usuarios
GET {{api}}/count

### Actualizar Usuario 
PUT {{api}}/1
Content-Type: application/json

{
  "id_usuario": 1,
  "nombre": "Super",
  "apellido": "admin",
  "correo": "attendace@gmail.com",
  "correo_respaldo": "Eladmin@soy.sena.edu.co",
  "num_documento": "0000000000",
  "num_contrato": "0000000",
  "num_contacto": "0000000000",
  "id_rol": 1,
  "contrasena": "1234",
  "estado_usuario": 1
}